<?php
session_start();
require 'db.php';
require_once 'schema_helpers.php';
if (!isset($_SESSION['user_id']) || !in_array($_SESSION['role'] ?? '', ['Admin', 'SuperAdmin', 'AssistantSuperAdmin', 'AssistantAdmin'], true)) { header('Location: login.php'); exit(); }
ensureRepairAutomationSchema($conn);
$result = $conn->query("SELECT tr.repair_id, tr.work_performed, tr.technician_notes, tr.updated_at, r.ebike_model, r.issue_description, r.amount, c.name AS customer_name, t.name AS technician_name, t.custom_id AS technician_id FROM technician_repair_reports tr INNER JOIN repairs r ON r.repair_id=tr.repair_id LEFT JOIN users c ON c.user_id=r.customer_id LEFT JOIN users t ON t.user_id=tr.technician_id WHERE r.repair_status='Completed' ORDER BY tr.updated_at DESC");
?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Service Reports - FixTrack</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet"></head>
<body><?php include 'navbaradmin.php'; ?><main class="dashboard-container"><div class="page-hero"><h1 class="h3 mb-1">Completed Repair Service Reports</h1><p>Only completed repair tickets are listed, with the technician who completed each job.</p></div><div class="card shadow-sm"><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>Repair</th><th>Customer</th><th>E-bike</th><th>Reported Issue</th><th>Work Performed</th><th>Technician</th><th>Total</th><th>Completed Report</th><th></th></tr></thead><tbody><?php if ($result && $result->num_rows): while ($report = $result->fetch_assoc()): ?><tr><td>#<?= htmlspecialchars((string)$report['repair_id']) ?></td><td><?= htmlspecialchars($report['customer_name'] ?? 'Customer') ?></td><td><?= htmlspecialchars($report['ebike_model']) ?></td><td><?= htmlspecialchars($report['issue_description']) ?></td><td><?= htmlspecialchars($report['work_performed'] ?: 'No work details submitted') ?></td><td><?= htmlspecialchars($report['technician_name'] ?: ($report['technician_id'] ?: 'Unassigned')) ?></td><td>PHP <?= number_format((float)$report['amount'], 2) ?></td><td><?= htmlspecialchars($report['updated_at']) ?></td><td><a class="btn btn-sm btn-outline-success" href="repairdetails.php?id=<?= urlencode((string)$report['repair_id']) ?>">View Details</a></td></tr><?php endwhile; else: ?><tr><td colspan="9" class="py-4 text-center text-muted">No completed repair reports yet.</td></tr><?php endif; ?></tbody></table></div></div></div></main></body></html>
